#!/bin/bash

domain=$(sudo yunohost app setting ghostblog domain)

sudo userdel --remove ghostblog

sudo service ynh-app-ghostblog stop
sudo update-rc.d ynh-app-ghostblog remove
sudo rm /etc/init.d/ynh-app-ghostblog
sudo yunohost app service -R ynh-app-ghostblog

sudo rm -f /etc/nginx/conf.d/$domain.d/ghostblog.conf

sudo rm -rf /var/run/yunohost/ghostblog