#!/bin/bash

domain=$(sudo yunohost app setting ghostblog domain)

sudo service ynh-ghostblog stop
sudo update-rc.d ynh-ghostblog remove
sudo rm /etc/init.d/ynh-ghostblog
sudo yunohost app service -R ynh-ghostblog
sudo rm -f /etc/nginx/conf.d/$domain.d/ghostblog.conf
sudo rm -f /var/log/ghostblog.log
sudo rm -rf /var/run/yunohost/ghostblog
sudo rm -f /etc/logrotate.d/ynh-ghostblog

# remove user so that it does not hold resource
sudo userdel --remove ghostblog
